name: pr-new-modules
run-name: Triggered by pr
env:
  GH_TOKEN: ${{ github.token }}
  PR: ${{ github.event.pull_request.html_url }}
on:
  pull_request_target:
    types:
      - opened
      - edited
jobs:
  process_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
    - name: check for new modules
      shell: pwsh
      env:
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.head_ref }}
      run: if((git diff $env:HEAD_REF $env:BASE_REF --diff-filter=A --name-only -- '**/*.sln').Count -gt 0) { Write-Host "Detected a new module" } else { Write-Host "No new module detected" }
